apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-microservice
  labels:
    app: sample-microservice   # optional, can be anything
spec:
  replicas: 3
  selector:
    matchLabels:
      app: example-microservice   # must match pod labels
  template:
    metadata:
      labels:
        app: example-microservice   # this is what your pods have
    spec:
      containers:
      - name: sample-microservice
        image: techwithswati/sample-microservice:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http                # named port for Prometheus
        env:
        - name: ENVIRONMENT
          value: "kubernetes"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: sample-microservice
spec:
  selector:
    app: example-microservice       # must match pod labels
  ports:
    - port: 80
      targetPort: 8080
      name: http
  type: LoadBalancer
